replicaCount: 1

image:
  repository: 192.168.2.92/jenkins/message-server
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: harbor-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 22339
  targetPort: 22339
  nodePort: 30001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

namespace:
  create: true
  name: message-server