# Production environment values
replicaCount: 1
image:
  tag: "v147"
service:
  nodePort: 30003
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 125m
    memory: 128Mi
namespace:
  name: message-server-prod
